
package vista;

import controlador.cArreglo;
import controlador.cCola_LE;
import controlador.cLE_Comprobante;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.cProducto;
import modelo.cBoleta;
import modelo.cFactura;
import modelo.cComprobante;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import modelo.cDetalle_Comprobante;
import modelo.cCliente;


/**
 *
 * @author Giuss
 */
public class frmGeneral extends javax.swing.JFrame {

    public static cArreglo arregloProductos = new cArreglo(1000);
    public static cLE_Comprobante leComprobante = new cLE_Comprobante();
    public static cCola_LE leCola = new cCola_LE();

    /**
     * Creates new form frmGeneral
     */
    public frmGeneral() {
        initComponents();
        cargarProductosBase();
        cargarComprobantesBase();
        cargarClientesBase();
        
        habilitarBotonesProductos();
        habilitarBotonesComprobantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //METODO PARA CARGAR LOS OBJETOS BASE
    private void mostrarProductos(JTable tableA) {
        arregloProductos.recorreLE(tableA);
    }
    
    private void mostrarComprobantes(JTable tableLE){
        leComprobante.recorreLE(tableLE);
    }
    
    private void mostrarClientes(JTable tableC){
    
        leCola.recorrerCola(tableC);
        
    }

    private void cargarProductosBase() {
        arregloProductos.agregar(new cProducto("LAPTOP - I7 13400k", 2999.99, 100));
        arregloProductos.agregar(new cProducto("MOUSE - LOGITECH G645", 119.99, 100));
        arregloProductos.agregar(new cProducto("TECLADO RGB - DRAGON", 249.99, 100));

        mostrarProductos(tableA);
    }
    
    private void cargarComprobantesBase() {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        String fecha1str = "02/04/2005";      
        String fecha2str = "04/09/2010";      
        String fecha3str = "07/10/2006";
        
        Date fecha1 = null;
        Date fecha2 = null;
        Date fecha3 = null;
        
        try {
            fecha1 = formato.parse(fecha1str);
            fecha2 = formato.parse(fecha2str);
            fecha3 = formato.parse(fecha3str);
        } catch (ParseException e) {
           System.out.println("Error al convertir una de las fechas:" + e.getMessage());
        }   
        
        cFactura f1 = new cFactura(fecha1,"C008","V002");
        cBoleta b1 = new cBoleta(fecha2,"C004", "V003");
        cFactura f2 = new cFactura(fecha3,"C002", "V001");
        
        f1.setDetalle(new cDetalle_Comprobante(f1.getCodigo(),
                        arregloProductos.obtener(0).getCodigo(),
                        2,
                        arregloProductos.obtener(0).getPrecio()));
        f1.setDetalle(new cDetalle_Comprobante(f1.getCodigo(),
                        arregloProductos.obtener(1).getCodigo(),
                        3,
                        arregloProductos.obtener(1).getPrecio()));
        
        b1.setDetalle(new cDetalle_Comprobante(b1.getCodigo(),
                        arregloProductos.obtener(0).getCodigo(),
                        3,
                        arregloProductos.obtener(0).getPrecio()));
        b1.setDetalle(new cDetalle_Comprobante(b1.getCodigo(),
                        arregloProductos.obtener(2).getCodigo(),
                        1,
                        arregloProductos.obtener(2).getPrecio()));
        
        f2.setDetalle(new cDetalle_Comprobante(f2.getCodigo(),
                        arregloProductos.obtener(0).getCodigo(),
                        1,
                        arregloProductos.obtener(0).getPrecio()));
        
        leComprobante.insertarxFinal(f1);
        leComprobante.insertarxFinal(b1);
        leComprobante.insertarxFinal(f2);

        mostrarComprobantes(tableLE);
    }
    
    private void cargarClientesBase() {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        String fecha1str = "02/04/2005";      
        String fecha2str = "04/09/2010";      
        String fecha3str = "07/10/2006";
        
        Date fecha1 = null;
        Date fecha2 = null;
        Date fecha3 = null;
        
        try {
            fecha1 = formato.parse(fecha1str);
            fecha2 = formato.parse(fecha2str);
            fecha3 = formato.parse(fecha3str);
        } catch (ParseException e) {
           System.out.println("Error al convertir una de las fechas:" + e.getMessage());
        }  
        
        
        long tel1= 991992990;
        long tel2= 959192231;
        long tel3= 910233677;
        
        long doc1=1078181921;
        long doc2= 76192192;
        long doc3=1071623251;
        
        
        
        leCola.incluir(new cCliente("Tenda",tel1,doc1,fecha1,2,"Lizardo Silva"));
        leCola.incluir(new cCliente("Juan Quillo",tel2,doc2,fecha2,1,"Juan Quillo"));
        leCola.incluir(new cCliente("Gatitas.com",tel3,doc3,fecha3,2,"Jesús Giussepe"));

        mostrarClientes(tableC);
    }
    
    
    

    //MÉTODOS PARA HABILITAR LOS BOTONES ACTUALIZAR & ELIMINAR
    private void habilitarBotonesProductos() {
        tableA.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { 
                boolean filaSeleccionada = tableA.getSelectedRow() != -1;
                btnActualizaA.setEnabled(filaSeleccionada);
                btnBorraA.setEnabled(filaSeleccionada);
            }
        });
    }
    
    private void habilitarBotonesComprobantes() {
        tableLE.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { 
                boolean filaSeleccionada = tableLE.getSelectedRow() != -1;
                btnActualizaLE.setEnabled(filaSeleccionada);
                btnBorraLE.setEnabled(filaSeleccionada);
            }
        });
    }

    //MÉTODOS PARA REFRESCAR LAS TABLAS (uso la logica de cuando se cierre un form externo se refresque por sí solo)
    private void refrescarTablaProd(javax.swing.JFrame ventana) {
        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                //aca uso el metodo para mostrar los productos en la tabla
                mostrarProductos(tableA);
            }
        });
    }
    
    private void refrescarTablaCompro(javax.swing.JFrame ventana) {
        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                //aca uso el metodo para mostrar los productos en la tabla
                mostrarComprobantes(tableLE);
            }
        });
    }
    
    
    private void refrescarTablaCli(javax.swing.JFrame ventana) {
        ventana.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                //aca uso el metodo para mostrar los productos en la tabla
                mostrarClientes(tableC);
            }
        });
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableA = new javax.swing.JTable();
        btnIngresaA = new javax.swing.JButton();
        btnActualizaA = new javax.swing.JButton();
        btnBorraA = new javax.swing.JButton();
        btnConsultaA = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableLE = new javax.swing.JTable();
        btnIngresaLE = new javax.swing.JButton();
        btnActualizaLE = new javax.swing.JButton();
        btnBorraLE = new javax.swing.JButton();
        btnConsultaLE = new javax.swing.JButton();
        panCompro = new javax.swing.JPanel();
        rbBol = new javax.swing.JRadioButton();
        rbFac = new javax.swing.JRadioButton();
        rbTodo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableC = new javax.swing.JTable();
        btnIngresaC = new javax.swing.JButton();
        btnActualizaC = new javax.swing.JButton();
        btnEliminaC = new javax.swing.JButton();
        panCliente = new javax.swing.JPanel();
        rbPersona = new javax.swing.JRadioButton();
        rbEmpresa = new javax.swing.JRadioButton();
        rbTodos = new javax.swing.JRadioButton();
        btnConsultaC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableP = new javax.swing.JTable();
        btnIngresaP = new javax.swing.JButton();
        btnActualizaP = new javax.swing.JButton();
        btnBorraP = new javax.swing.JButton();
        btnConsultaP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnIntegrantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Precio", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tableA);

        btnIngresaA.setText("Añadir");
        btnIngresaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresaAActionPerformed(evt);
            }
        });

        btnActualizaA.setText("Actualizar");
        btnActualizaA.setEnabled(false);
        btnActualizaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaAActionPerformed(evt);
            }
        });

        btnBorraA.setText("Eliminar");
        btnBorraA.setEnabled(false);
        btnBorraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorraAActionPerformed(evt);
            }
        });

        btnConsultaA.setText("Consultar");
        btnConsultaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIngresaA)
                        .addGap(56, 56, 56)
                        .addComponent(btnActualizaA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(btnBorraA)
                        .addGap(54, 54, 54)
                        .addComponent(btnConsultaA)))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresaA)
                    .addComponent(btnActualizaA)
                    .addComponent(btnBorraA)
                    .addComponent(btnConsultaA))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Productos", jPanel1);

        tableLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Fecha", "Código_Cliente", "Código_Vendedor", "Subotal", "Total"
            }
        ));
        jScrollPane2.setViewportView(tableLE);

        btnIngresaLE.setText("Añadir");
        btnIngresaLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresaLEActionPerformed(evt);
            }
        });

        btnActualizaLE.setText("Actualizar");
        btnActualizaLE.setEnabled(false);
        btnActualizaLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaLEActionPerformed(evt);
            }
        });

        btnBorraLE.setText("Eliminar");
        btnBorraLE.setEnabled(false);
        btnBorraLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorraLEActionPerformed(evt);
            }
        });

        btnConsultaLE.setText("Consultar");
        btnConsultaLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaLEActionPerformed(evt);
            }
        });

        panCompro.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar"));

        buttonGroup2.add(rbBol);
        rbBol.setText("Boleta");
        rbBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBolActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbFac);
        rbFac.setText("Factura");
        rbFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFacActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbTodo);
        rbTodo.setText("Todos");
        rbTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panComproLayout = new javax.swing.GroupLayout(panCompro);
        panCompro.setLayout(panComproLayout);
        panComproLayout.setHorizontalGroup(
            panComproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panComproLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbBol)
                .addGap(18, 18, 18)
                .addComponent(rbFac)
                .addGap(18, 18, 18)
                .addComponent(rbTodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panComproLayout.setVerticalGroup(
            panComproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panComproLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panComproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBol)
                    .addComponent(rbFac)
                    .addComponent(rbTodo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnIngresaLE)
                .addGap(41, 41, 41)
                .addComponent(btnActualizaLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorraLE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaLE)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(panCompro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresaLE)
                    .addComponent(btnActualizaLE)
                    .addComponent(btnBorraLE)
                    .addComponent(btnConsultaLE))
                .addGap(18, 18, 18)
                .addComponent(panCompro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comprobantes", jPanel2);

        tableC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Razón Social", "Teléfono", "DNI/RUC", "Fecha_Compra", "Tipo", "Contacto"
            }
        ));
        jScrollPane3.setViewportView(tableC);

        btnIngresaC.setText("Añadir");
        btnIngresaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresaCActionPerformed(evt);
            }
        });

        btnActualizaC.setText("Actualizar");
        btnActualizaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaCActionPerformed(evt);
            }
        });

        btnEliminaC.setText("Eliminar");
        btnEliminaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaCActionPerformed(evt);
            }
        });

        panCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar"));

        buttonGroup1.add(rbPersona);
        rbPersona.setText("Persona Natural");
        rbPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPersonaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbEmpresa);
        rbEmpresa.setText("Empresa");
        rbEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEmpresaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTodos);
        rbTodos.setText("Todos");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panClienteLayout = new javax.swing.GroupLayout(panCliente);
        panCliente.setLayout(panClienteLayout);
        panClienteLayout.setHorizontalGroup(
            panClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbPersona)
                .addGap(18, 18, 18)
                .addComponent(rbEmpresa)
                .addGap(18, 18, 18)
                .addComponent(rbTodos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panClienteLayout.setVerticalGroup(
            panClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPersona)
                    .addComponent(rbEmpresa)
                    .addComponent(rbTodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConsultaC.setText("Consultar");
        btnConsultaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnIngresaC)
                        .addGap(51, 51, 51)
                        .addComponent(btnActualizaC)
                        .addGap(60, 60, 60)
                        .addComponent(btnEliminaC)
                        .addGap(62, 62, 62)
                        .addComponent(btnConsultaC)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(panCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizaC)
                    .addComponent(btnEliminaC)
                    .addComponent(btnIngresaC)
                    .addComponent(btnConsultaC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("Clientes", jPanel3);

        tableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Fecha de Ingreso", "Sueldo", "Cargo"
            }
        ));
        jScrollPane4.setViewportView(tableP);

        btnIngresaP.setText("Añadir");

        btnActualizaP.setText("Actualizar");
        btnActualizaP.setEnabled(false);

        btnBorraP.setText("Eliminar");
        btnBorraP.setEnabled(false);

        btnConsultaP.setText("Consultar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnIngresaP)
                        .addGap(56, 56, 56)
                        .addComponent(btnActualizaP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(btnBorraP)
                        .addGap(40, 40, 40)
                        .addComponent(btnConsultaP))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresaP)
                    .addComponent(btnActualizaP)
                    .addComponent(btnBorraP)
                    .addComponent(btnConsultaP))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Trabajadores", jPanel4);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("GESTIÓN GENERAL");

        btnIntegrantes.setText("Integrantes");
        btnIntegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegrantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126)
                .addComponent(btnIntegrantes)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnIntegrantes))
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //BOTONES DE LA PESTAÑA PRODUCTOS
    private void btnIngresaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresaAActionPerformed
        //ABRE CON EL CONSTRUCTOR PARA AÑADIR 
        frmProductoAdd ventana = new frmProductoAdd();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnIngresaAActionPerformed

    private void btnActualizaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaAActionPerformed
        //ABRE CON EL CONSTRUCTOR PARA ACTUALIZAR
        cProducto producto = arregloProductos.obtener(tableA.getSelectedRow());
        frmProductoAdd ventana = new frmProductoAdd(producto); // pasa el producto existente mediante el objeto

        refrescarTablaProd(ventana);

        ventana.setVisible(true);
    }//GEN-LAST:event_btnActualizaAActionPerformed

    private void btnBorraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorraAActionPerformed
        cProducto p= arregloProductos.obtener(tableA.getSelectedRow());
        
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar este producto?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        
        if (opcion==JOptionPane.YES_OPTION) {
            arregloProductos.eliminar(p.getCodigo());
            JOptionPane.showMessageDialog(this, "Producto eliminado correctamente");
            mostrarProductos(tableA);
        }
    }//GEN-LAST:event_btnBorraAActionPerformed

    private void btnConsultaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaAActionPerformed
        frmProductoSee ventana= new frmProductoSee();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnConsultaAActionPerformed

    
    //BOTÓN DE INTEGRANTES
    private void btnIntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegrantesActionPerformed
        frmIntegrantes integrantes = new frmIntegrantes();
        integrantes.setVisible(true);
    }//GEN-LAST:event_btnIntegrantesActionPerformed

    
    
    //BOTONES DE LA PESTAÑA COMPROBANTES
    private void btnIngresaLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresaLEActionPerformed
        frmComprobanteAdd ventana = new frmComprobanteAdd();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnIngresaLEActionPerformed

    private void btnActualizaLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaLEActionPerformed
        int fila = tableLE.getSelectedRow();
        String codigo =String.valueOf(tableLE.getValueAt(fila, 0));
        cComprobante comprobante = leComprobante.busqueda(codigo);
        frmComprobanteAdd ventana = new frmComprobanteAdd(comprobante);

        refrescarTablaCompro(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnActualizaLEActionPerformed

    private void btnBorraLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorraLEActionPerformed
        int fila = tableLE.getSelectedRow();
        
        String codigo =String.valueOf(tableLE.getValueAt(fila, 0));
        
        cComprobante c = leComprobante.busqueda(codigo);
        
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar este comprobante?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        
        if (opcion==JOptionPane.YES_OPTION) {
            leComprobante.eliminaEntreNodos(c.getCodigo());
            JOptionPane.showMessageDialog(this, "Comprobante eliminado correctamente");
            //mostrarProductos(arregloProductos);
        }
    }//GEN-LAST:event_btnBorraLEActionPerformed

    private void btnConsultaLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaLEActionPerformed
        
            frmComprobanteSee ventana = new frmComprobanteSee();
            
            ventana.setVisible(true);

    }//GEN-LAST:event_btnConsultaLEActionPerformed
    
    
    //BOTONES DE LA PESTAÑA CLIENTES
    private void btnIngresaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresaCActionPerformed
        frmClienteAdd  ventana= new frmClienteAdd();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnIngresaCActionPerformed

    private void btnActualizaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaCActionPerformed
        cCliente cliente = leCola.acceso();
        frmClienteAdd ventana = new frmClienteAdd(cliente);

        refrescarTablaCli(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnActualizaCActionPerformed

    private void btnEliminaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaCActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar al cliente?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        
        if (opcion==JOptionPane.YES_OPTION) {
           leCola.eliminar();
            JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente");
            //mostrarProductos(arregloProductos);
        }  
        
    }//GEN-LAST:event_btnEliminaCActionPerformed

    private void btnConsultaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCActionPerformed
        
            frmClienteSee ventana = new frmClienteSee();
            ventana.setVisible(true);

    }//GEN-LAST:event_btnConsultaCActionPerformed
    
    
    //FILTROS DE CLIENTES
    private void rbPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPersonaActionPerformed
        leCola.recorrerColaP(tableC);
    }//GEN-LAST:event_rbPersonaActionPerformed

    private void rbEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEmpresaActionPerformed
        leCola.recorrerColaE(tableC);
    }//GEN-LAST:event_rbEmpresaActionPerformed

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        mostrarClientes(tableC);
    }//GEN-LAST:event_rbTodosActionPerformed

    
    //FILTROS PARA COMPROBANTES
    private void rbBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBolActionPerformed
        leComprobante.recorreLEBoleta(tableLE);
    }//GEN-LAST:event_rbBolActionPerformed

    private void rbFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFacActionPerformed
        leComprobante.recorreLEFactura(tableLE);
    }//GEN-LAST:event_rbFacActionPerformed

    private void rbTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodoActionPerformed
        mostrarComprobantes(tableLE);
    }//GEN-LAST:event_rbTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        // Activa el look and feel "Nimbus" (moderno por defecto en NetBeans)
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(frmGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
        new frmGeneral().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizaA;
    private javax.swing.JButton btnActualizaC;
    private javax.swing.JButton btnActualizaLE;
    private javax.swing.JButton btnActualizaP;
    private javax.swing.JButton btnBorraA;
    private javax.swing.JButton btnBorraLE;
    private javax.swing.JButton btnBorraP;
    private javax.swing.JButton btnConsultaA;
    private javax.swing.JButton btnConsultaC;
    private javax.swing.JButton btnConsultaLE;
    private javax.swing.JButton btnConsultaP;
    private javax.swing.JButton btnEliminaC;
    private javax.swing.JButton btnIngresaA;
    private javax.swing.JButton btnIngresaC;
    private javax.swing.JButton btnIngresaLE;
    private javax.swing.JButton btnIngresaP;
    private javax.swing.JButton btnIntegrantes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panCliente;
    private javax.swing.JPanel panCompro;
    private javax.swing.JRadioButton rbBol;
    private javax.swing.JRadioButton rbEmpresa;
    private javax.swing.JRadioButton rbFac;
    private javax.swing.JRadioButton rbPersona;
    private javax.swing.JRadioButton rbTodo;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JTable tableA;
    private javax.swing.JTable tableC;
    private javax.swing.JTable tableLE;
    private javax.swing.JTable tableP;
    // End of variables declaration//GEN-END:variables
}
