/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.cUsuario;

/**
 *
 * @author adria
 */
public class frmLogin extends javax.swing.JPanel {

     cUsuario oUsuario = new cUsuario("admin","lavidaescorta123");
    public frmLogin() {
        initComponents();
       
    }
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {                                            

        if(!txtUsuario.getText().trim().isEmpty() && !psContraseña.getText().trim().isEmpty()){

            String usuario = txtUsuario.getText();

            String contraseña= psContraseña.getText();

            if(usuario.equals(oUsuario.getUsuario())&& contraseña.equals(oUsuario.getContraseña())){

                frmGeneral frmGeneral = new frmGeneral();

                frmGeneral.setVisible(true);

                this.setVisible(false);

            }else{

                JOptionPane.showMessageDialog(this, "Usuario o Contraseña incorrectos :p");

            }   

        }else{

            JOptionPane.showMessageDialog(this, "Complete todos los campos");

        }

    }                             

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */public static void main(String[] args) {
        
         
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        psContraseña = new javax.swing.JPasswordField();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/resources/panel_1.png"))); // NOI18N
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, -10, 660, 680));

        txtUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese su usuario");
        txtUsuario.setBorder(null);
        background.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 330, 20));

        btnIngresar.setBackground(new java.awt.Color(153, 153, 153));
        btnIngresar.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        background.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 150, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setText("INICIAR SESIÓN");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 430, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Usuario:");
        jLabel4.setToolTipText("Ingrese su usuario");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 100, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Contraseña:");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 160, 40));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 330, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 340, 30));

        psContraseña.setForeground(new java.awt.Color(204, 204, 204));
        psContraseña.setText("jPasswordField1");
        psContraseña.setBorder(null);
        background.add(psContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 330, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPasswordField psContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
